name: "Health Check"

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  healthcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Release API Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: "ps-api.soongsil-computing.club"
          max-attempts: 3
          retry-delay: 1s
