# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SOLVEDAC_TOKEN: ${{ secrets.SOLVEDAC_TOKEN }}
      BOJ_AUTO_LOGIN: ${{ secrets.BOJ_AUTO_LOGIN }}
      BOJ_USER_AGENT: ${{ secrets.BOJ_USER_AGENT }}
      CLIST_API_KEY: ${{ secrets.CLIST_API_KEY }}

    strategy:
      matrix:
        node-version: [ 23.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Generate Environment Variables File for Production
        run: |
          cat <<EOF > .env
          PORT="${PORT}"
          MONGODB_URI="${MONGODB_URI}"
          SOLVEDAC_TOKEN="${SOLVEDAC_TOKEN}"
          BOJ_AUTO_LOGIN="${BOJ_AUTO_LOGIN}"
          BOJ_USER_AGENT="${BOJ_USER_AGENT}"
          CLIST_API_KEY="${CLIST_API_KEY}"
          EOF

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
